Resources:
  Inventory:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: item
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST